# Generated by Django 4.2.3 on 2023-08-01 12:59

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='место')),
                ('time', models.TimeField(default=datetime.datetime(2023, 8, 1, 15, 59, 46, 509202), verbose_name='время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('good_habit_sign', models.BooleanField(default=False, verbose_name='признак хорошей привычки')),
                ('frequency', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=7, message='Не может быть реже 1 раза в неделю')], verbose_name='Периодичность')),
                ('reward', models.CharField(max_length=255, verbose_name='награда')),
                ('time_to_complete', models.DurationField(default=datetime.timedelta(seconds=120), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120), message='Не может быть больше 120 секунд')], verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='habit.habit')),
            ],
        ),
    ]
