# Generated by Django 4.2.3 on 2023-08-01 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 1, 16, 1, 10, 915192), verbose_name='время'),
        ),
    ]
