# Generated by Django 4.2.3 on 2023-08-02 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_habit_options_alter_habit_related_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='habit.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 2, 11, 34, 18, 234481), verbose_name='время'),
        ),
    ]
