# Generated by Django 4.2.3 on 2023-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_alter_habit_reward_alter_habit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='tg_chat_id',
            field=models.TextField(blank=True, null=True, verbose_name='id чата в телеграме'),
        ),
    ]
